INSERT INTO TIPOCAMBIO(ID_MONEDAORIGEN, ID_MONEDADESTINO, DE_VALORCAMBIO, DT_FECHACREA, VC_USUARIOCREA, CH_ESTADO) VALUES('PEN', 'USD', 3.90, SYSDATE(), 'USERCRT', true);
INSERT INTO TIPOCAMBIO(ID_MONEDAORIGEN, ID_MONEDADESTINO, DE_VALORCAMBIO, DT_FECHACREA, VC_USUARIOCREA, CH_ESTADO) VALUES('USD', 'PEN', 3.60, SYSDATE(), 'USERCRT', true);
INSERT INTO TIPOCAMBIO(ID_MONEDAORIGEN, ID_MONEDADESTINO, DE_VALORCAMBIO, DT_FECHACREA, VC_USUARIOCREA, CH_ESTADO) VALUES('PEN', 'EUR', 4.90, SYSDATE(), 'USERCRT', true);
INSERT INTO TIPOCAMBIO(ID_MONEDAORIGEN, ID_MONEDADESTINO, DE_VALORCAMBIO, DT_FECHACREA, VC_USUARIOCREA, CH_ESTADO) VALUES('EUR', 'PEN', 4.40, SYSDATE(), 'USERCRT', true);
INSERT INTO TIPOCAMBIO(ID_MONEDAORIGEN, ID_MONEDADESTINO, DE_VALORCAMBIO, DT_FECHACREA, VC_USUARIOCREA, CH_ESTADO) VALUES('USD', 'EUR', 1.19, SYSDATE(), 'USERCRT', true);
INSERT INTO TIPOCAMBIO(ID_MONEDAORIGEN, ID_MONEDADESTINO, DE_VALORCAMBIO, DT_FECHACREA, VC_USUARIOCREA, CH_ESTADO) VALUES('EUR', 'USD', 0.84, SYSDATE(), 'USERCRT', true);
